openapi: 3.0.1
info:
  description: douyin open api
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: 抖音开放API
  version: 1.0.0
servers:
- url: https://open.douyin.com/
tags:
- description: oauth
  name: oauth
paths:
  /connect:
    post:
      description: 获取授权码(code)
      operationId: connect
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConnectReq'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResponse'
          description: successful operation
      summary: 获取授权码(code)
      tags:
      - oauth
      x-codegen-request-body-name: body
components:
  schemas:
    ConnectReq:
      example:
        client_key: client_key
        scope: scope
        response_type: response_type
        optionalScope: optionalScope
        redirect_uri: redirect_uri
        state: state
      properties:
        client_key:
          description: 应用唯一标识
          type: string
        response_type:
          description: 填写code
          type: string
        scope:
          description: 应用授权作用域,多个授权作用域以英文逗号（,）分隔
          type: string
        optionalScope:
          description: 应用授权可选作用域,多个授权作用域以英文逗号（,）分隔，每一个授权作用域后需要加上一个是否默认勾选的参数，1为默认勾选，0为默认不勾选
          type: string
        redirect_uri:
          description: 授权成功后的回调地址，必须以http/https开头。域名必须对应申请应用时填写的域名，如不清楚请联系应用申请人。
          type: string
        state:
          description: 用于保持请求和回调的状态
          type: string
      type: object
    APIResponse:
      description: ""
      example:
        data:
          description: description
          error_code: 0
        extra:
          now: 6
          logid: logid
      properties:
        data:
          $ref: '#/components/schemas/APIResponse_data'
        extra:
          $ref: '#/components/schemas/APIResponse_extra'
      title: APIResponse
      type: object
    APIResponse_data:
      example:
        description: description
        error_code: 0
      properties:
        description:
          type: string
        error_code:
          format: int32
          type: integer
    APIResponse_extra:
      example:
        now: 6
        logid: logid
      properties:
        logid:
          type: string
        now:
          format: int64
          type: integer
